server:
  port: 3344
 
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:  #git@github.com:qq1512050510/microservicecloud-config.git
          uri: git://github.com/qq1512050510/microservicecloud-config.git #GitHub上面的git仓库名字
          
          
# windows下修改host文件 127.0.0.1 config-3344.com