server:
  port: 8601
  servlet:
   context-path: /demo
   
logging:
  #配置日志文件路径
  path: ./log
  level:
    learning: trace
    #com.imu.mapper : trace#mybatis打印sql
    com.imu.mapper : debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.mybatis: info
    #控制台打印log
   
spring:
    datasource:
        name: test
        url: jdbc:mysql://47.104.100.129:3306/imu?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true 
        username: imu
        password: cde3$5tgbVFR
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        #druid:
        #   url: jdbc:mysql://127.0.0.1:3306/imu?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true 
        #   username: root
        #   password: success
        #   driver-class-name: com.mysql.cj.jdbc.Driver
    #thymeleaf 基本配置
    thymeleaf:  
        cache: false  
        prefix: classpath:/templates/  
        suffix: .html  
        encoding: UTF-8  
        servlet:
          content-type: text/html  
        mode: HTML5  
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.winter.model
  
mybatis:
  #实体类所做包
  type-aliases-package: com.imu.model
  #mapper.xml所在位置
  #mapper-locations: classpath:mappers/*.xml
  mapper-locations: classpath:com/imu/mapper/*.xml
#pagehelper分页插件

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
wechat:
  appId: wx5d53946d59f5e417
  appSecret: 995ef20a24e664adbd627147f1b44a89
  token: imu
    