server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
zuul:
  #前缀  url:myzuul.com:9527/chiang/mydept/dept/get/1
  prefix: /chiang
  #忽略url1
  ignored-services: microservicecloud-dept
  #忽略所有
  #ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    
    
#url1: myzuul.com:9527/microservicecloud-dept/dept/get/1
#url: myzuul.com:9527/mydept/dept/get/1
 
#zuul: 
  #ignored-services: microservicecloud-dept
#  prefix: /atguigu
#  ignored-services: "*"
#  routes: 
#    mydept.serviceId: microservicecloud-dept
#    mydept.path: /mydept/**
 
info:
  app.name: chiang-microcloud
  company.name: www.chiang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

